// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InspectPath(arg1) {
  return window['go']['main']['App']['InspectPath'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickZipFile() {
  return window['go']['main']['App']['PickZipFile']();
}
