// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddApplication(arg1:string):Promise<Array<main.ApplicationEntry>>;

export function AddServer(arg1:main.AddServerInput):Promise<void>;

export function Deploy(arg1:main.DeployInput):Promise<main.DeploymentInfo>;

export function GetDeploymentStatus(arg1:string):Promise<main.DeploymentInfo>;

export function ListApplications():Promise<Array<main.ApplicationEntry>>;

export function ListDeployments():Promise<Array<main.DeploymentInfo>>;

export function ListServers():Promise<Array<main.ServerInfo>>;

export function PickDirectory():Promise<string>;

export function PickZipFile():Promise<string>;

export function ReinspectApplication(arg1:string):Promise<main.ApplicationEntry>;

export function RemoveApplication(arg1:string):Promise<void>;

export function RemoveDeployment(arg1:string):Promise<void>;

export function RemoveServer(arg1:string):Promise<void>;

export function RestartDeployment(arg1:string):Promise<void>;

export function StopDeployment(arg1:string):Promise<void>;

export function StopDeploymentLogs(arg1:string):Promise<void>;

export function StreamDeploymentLogs(arg1:string):Promise<void>;

export function TestServer(arg1:string):Promise<void>;
