// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddApplication(arg1) {
  return window['go']['main']['App']['AddApplication'](arg1);
}

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function Deploy(arg1) {
  return window['go']['main']['App']['Deploy'](arg1);
}

export function GetDeploymentStatus(arg1) {
  return window['go']['main']['App']['GetDeploymentStatus'](arg1);
}

export function ListApplications() {
  return window['go']['main']['App']['ListApplications']();
}

export function ListDeployments() {
  return window['go']['main']['App']['ListDeployments']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickZipFile() {
  return window['go']['main']['App']['PickZipFile']();
}

export function ReinspectApplication(arg1) {
  return window['go']['main']['App']['ReinspectApplication'](arg1);
}

export function RemoveApplication(arg1) {
  return window['go']['main']['App']['RemoveApplication'](arg1);
}

export function RemoveDeployment(arg1) {
  return window['go']['main']['App']['RemoveDeployment'](arg1);
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}

export function RestartDeployment(arg1) {
  return window['go']['main']['App']['RestartDeployment'](arg1);
}

export function StopDeployment(arg1) {
  return window['go']['main']['App']['StopDeployment'](arg1);
}

export function StopDeploymentLogs(arg1) {
  return window['go']['main']['App']['StopDeploymentLogs'](arg1);
}

export function StreamDeploymentLogs(arg1) {
  return window['go']['main']['App']['StreamDeploymentLogs'](arg1);
}

export function TestServer(arg1) {
  return window['go']['main']['App']['TestServer'](arg1);
}
