// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function InspectPath(arg1:string):Promise<Array<main.AppInfo>>;

export function PickDirectory():Promise<string>;

export function PickZipFile():Promise<string>;
